--1. 사원번호,사원명,부서명을 조회하시오.
SELECT E.EMPLOYEE_ID,E.FIRST_NAME || E.LAST_NAME,D.DEPARTMENT_NAME
FROM DEPARTMENTS D INNER JOIN EMPLOYEES E
ON D.DEPARTMENT_ID = E.DEPARTMENT_ID;
--2.부서번호,부서명,지역명을 조회하시오.
SELECT D.DEPARTMENT_ID ,D.DEPARTMENT_NAME,l.street_address
FROM DEPARTMENTS D INNER JOIN LOCATIONS L
ON D.LOCATION_ID = L.LOCATION_ID;

--3.사원번호,사원명,직업,직업별 최대연봉,연봉을 조회하시오.
SELECT E.EMPLOYEE_ID,E.LAST_NAME,E.JOB_ID,J.MAX_SALARY,E.SALARY
FROM JOBS J INNER JOIN EMPLOYEES E
ON J.JOB_ID = E.DEPARTMENT_ID;

--외부 조인


--4. 사원번호,사원명,부서명을 조회하시오. 부서가 없으면 '부서없음'으로 조회하시오.
SELECT E.EMPLOYEE_ID,E.LAST_NAME,NVL(D.DEPARTMENT_NAME ,'부서없음')
FROM DEPARTMENTS D RIGHT JOIN EMPLOYEES E
ON D.DEPARTMENT_ID = E.DEPARTMENT_ID;
--5. 부서별 평균급여를 조회하시오. 부서명,평균 급여를 조회하시오. 근무중인 사원이 없으면 평균급여를 0으로 조회하시오.
SELECT D.DEPARTMENT_NAME, NVL(AVG(E.SALARY),0)
FROM DEPARTMENTS D LEFT JOIN EMPLOYEES E
ON D.DEPARTMENT_ID = E.DEPARTMENT_ID
GROUP BY D.DEPARTMENT_ID, D.DEPARTMENT_NAME;
--3개 이상 테이블 조인하기

--6. 사원번호,사원명,부서번호,부서명,지역번호,지역명을 조회하시오.
SELECT E.EMPLOYEE_ID,E.LAST_NAME,D.DEPARTMENT_ID,D.DEPARTMENT_NAME,L.LOCATION_ID,L.STREET_ADDRESS,L.LOCATION_ID,L.STREET_ADDRESS
FROM DEPARTMENTS D INNER JOIN EMPLOYEES E
ON D.DEPARTMENT_ID = E.DEPARTMENT_ID INNER JOIN LOCATIONS L
ON D.LOCATION_ID = L. LOCATION_ID;

SELECT E.EMPLOYEE_ID,E.LAST_NAME,D.DEPARTMENT_ID,D.DEPARTMENT_NAME,L.LOCATION_ID,L.STREET_ADDRESS,L.LOCATION_ID,L.STREET_ADDRESS
FROM LOCATIONS L INNER JOIN DEPARTMENTS D
ON L.LOCATION_ID = D.LOCATION_ID INNER JOIN EMPLOYEES E
ON D.DEPARTMENT_ID = E.DEPARTMENT_ID;

--7. 국가명,도시명,부서명을 조회하시오.
SELECT C.COUNTRY_NAME, L.CITY, D.DEPARTMENT_NAME 
FROM COUNTRIES C INNER JOIN LOCATIONS L
ON c.country_id = L.COUNTRY_ID INNER JOIN DEPARTMENTS D
ON L.LOCATION_ID = D.LOCATION_ID;

--셀프 조인 (하나의 테이블에 일대다 관계를 가지는 칼럼들이 존재하는 경우)

--8.사원번호,사원명,매니저 번호,매니저 명을 조회하시오.
--관계
--1명의 매니저가 N명의 사원을 관리한다.
--사원테이블 : EMPLOYEES E
--(1)매니저 테이블: EMPLOYEES M       : (M)사원 테이블: EMPLOYEES E
--PK  EMPLOYEE_ID                                        FK  MANAGER_ID
--매니저가 1ㅇ순위
--조인조건:

SELECT E.EMPLOYEE_ID AS 사원번호,
       E.LAST_NAME AS 사원명,
       E.MANAGER_ID AS 매니저번호,
       M.LAST_NAME AS 매니저명
FROM EMPLOYEES M
INNER JOIN EMPLOYEES E ON M.EMPLOYEE_ID = E.MANAGER_ID;

--9.  같은 부서내에서 나보다 급여를 더 많이 받는 사원을 조회하시오.
--관계
--나는 여러 사원과 관계를 맺는다.
--나(EMPLOYEES ME)                 너님들(EMPLOYEES YOU)
--
SELECT M. EMPLOYEE_ID AS 사원번호 ,M.LAST_NAME AS 사원명,M.SALARY AS급여,Y.EMPLOYEE_ID AS 너사원번호,Y.LAST_NAME AS 너사원명,Y.SALARY AS 너급여
FROM EMPLOYEES M INNER JOIN EMPLOYEES Y
ON M.DEPARTMENT_ID =Y.DEPARTMENT_ID
WHERE Y.SALARY > M.SALARY 
AND M.DEPARTMENT_ID = 50; 




-- 1. LOCATION_ID가 1700인 부서에 근무하는 사원들의 EMPLOYEE_ID, FIRST_NAME, DEPARTMENT_NAME을 조회하시오.
SELECT E.EMPLOYEE_ID,E.FIRST_NAME,D.DEPARTMENT_NAME
FROM DEPARTMENTS D INNER JOIN EMPLOYEES E
ON D.DEPARTMENT_ID = E.DEPARTMENT_ID
WHERE D.LOCATION_ID = 1700;

-- 2. DEPARTMENT_NAME이 'Executive'인 부서에 근무하는 사원들의 EMPLOYEE_ID, FIRST_NAME을 조회하시오.
SELECT E.EMPLOYEE_ID, E.FIRST_NAME
FROM DEPARTMENTS D INNER JOIN EMPLOYEES E
ON  D.DEPARTMENT_ID = E.DEPARTMENT_ID
WHERE D.DEPARTMENT_NAME = 'Executive';

-- 3. 모든 사원들의 EMPLOYEE_ID, FIRST_NAME, DEPARTMENT_NAME, STREET_ADDRESS, CITY를 조회하시오.
SELECT E.EMPLOYEE_ID,E.FIRST_NAME,D.DEPARTMENT_NAME,L.STREET_ADDRESS,L.CITY
FROM DEPARTMENTS D INNER JOIN EMPLOYEES E
ON  D.DEPARTMENT_ID = E.DEPARTMENT_ID INNER JOIN LOCATIONS L
ON  D.LOCATION_ID = L.LOCATION_ID;

-- 4. 사원이 근무 중인 부서를 대상으로 DEPARTMENT_NAME과 근무 중인 사원 수와 평균 연봉을 조회하시오.
SELECT D.DEPARTMENT_NAME, COUNT(EMPLOYEE_ID),AVG(E.SALARY)
FROM DEPARTMENTS D RIGHT JOIN EMPLOYEES E
ON  D.DEPARTMENT_ID = E.DEPARTMENT_ID
GROUP BY D.DEPARTMENT_NAME;

-- 5. JOB_HISTORY 테이블에 존재하는 사원들을 대상으로 사원번호, 현재 JOB_ID, 예전 JOB_ID를 조회하시오.
SELECT E.EMPLOYEE_ID, E.JOB_ID,J.JOB_ID
FROM EMPLOYEES E INNER JOIN JOB_HISTORY J
ON E.EMPLOYEE_ID = J.EMPLOYEE_ID;

-- 6. 모든 사원들의 EMPLOYEE_ID, FIRST_NAME, DEPARTMENT_NAME을 조회하시오. 부서가 없는 사원의 부서명은 'None'으로 조회되도록 처리하시오.
SELECT E.EMPLOYEE_ID,E.FIRST_NAME,NVL(D.DEPARTMENT_NAME,'None')
FROM DEPARTMENTS D LEFT JOIN EMPLOYEES E
ON D.DEPARTMENT_ID = E.DEPARTMENT_ID;

-- 7. 모든 부서의 DEPARTMENT_NAME과 근무 중인 사원 수를 조회하시오. 근무하는 사원이 없으면 0으로 조회하시오.
SELECT D.DEPARTMENT_NAME, NVL(COUNT(E.EMPLOYEE_ID),0)
FROM DEPARTMENTS D LEFT JOIN EMPLOYEES E
ON  D.DEPARTMENT_ID = E.DEPARTMENT_ID
GROUP BY D.DEPARTMENT_NAME;


-- 8. 모든 부서의 DEPARTMENT_ID, DEPARTMENT_NAME, STATE_PROVINCE, COUNTRY_NAME, REGION_NAME을 조회하시오.
SELECT D.DEPARTMENT_ID,D.DEPARTMENT_NAME,L.STATE_PROVINCE,C.COUNTRY_NAME,R.REGION_NAME
FROM departments D INNER JOIN LOCATIONS L
ON D.LOCATION_ID = L.LOCATION_ID INNER JOIN COUNTRIES C
ON c.country_id = l.country_id INNER JOIN REGIONS R
ON R.REGION_ID = c.region_id ;



