/*
   샘플 테이블
*/
CREATE TABLE SAMPLE_T (
   NAME VARCHAR2(20 BYTE),
   KOR NUMBER(3),
   ENG NUMBER(3),
   MATH NUMBER(3)
);

INSERT INTO SAMPLE_T(NAME,KOR,ENG,MATH) VALUES('A',100,100,NULL);
INSERT INTO SAMPLE_T(NAME,KOR,ENG,MATH) VALUES('B',100,NULL,100);
INSERT INTO SAMPLE_T(NAME,KOR,ENG,MATH) VALUES('C',NULL,100,100);

